### ISSUE TITLE
APM/crumbs support for `sqflite`

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart#1201]
### Description

https://pub.dev/packages/sqflite

**Comment by marandaneto** [comment]
We'd need to find out if there's any interceptor we can hook to otherwise try to submit a feature request/upstream PR directly on the sqflite repo.

**Comment by ueman** [comment]
On a related note, people are often not using `sqflite` directly, but they're using it via [`drift`](https://pub.dev/packages/drift) or [`floor`](https://pub.dev/packages/floor).

I'm not aware of an interceptor or similar in sqflite, but since the API is basically stable, you could just write a wrapper for the [`Database`](https://pub.dev/documentation/sqflite_common/latest/sqlite_api/Database-class.html) class, which then does the tracing. It's then pretty similar to the `HttpClient`.

**Comment by kuhnroyal** [comment]
I have a simple wrapper for `drift`, works well. Using the device provided `sqlite` is a no-go for me but `sqflite` has 3.5k stars, so people are using it.

**Comment by ueman** [comment]
Interesting, I thought drift is using sqflite under the hood, but that's indeed not the case. @kuhnroyal Do you mind sharing your wrapper as a gist or something?

**Comment by kuhnroyal** [comment]
@ueman Check out https://gist.github.com/kuhnroyal/820caf5c9942c744204a6f0627e8dfa9

**Comment by marandaneto** [comment]
I've opened a [feature request](https://github.com/tekartik/sqflite/issues/928) for a much more user-friendly API, the current approach shared by @kuhnroyal would work but it's hacky, I mean it's using its APIs but it should be much easier.
@ueman suggestion as well, a Database wrapper would be possible.
