### ISSUE TITLE
Add tags for `PlatformException`

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#1231]
A lot of plugins just throw a [`PlatformException`](https://api.flutter.dev/flutter/services/PlatformException-class.html). That makes it hard to distinguish between those exceptions because they're used everywhere.

In order to better filter `PlatformExceptions` on Sentry, it would be nice to be able to filter based on [`PlatformException.code`](https://api.flutter.dev/flutter/services/PlatformException/code.html) and maybe on [`PlatformException.message`](https://api.flutter.dev/flutter/services/PlatformException/message.html) (though not to sure about this). Therefore, I suggest to add those fields as tags to events with a `PlatformException`.

**Comment by marandaneto** [comment]
@ueman the `message` can be part of the `SentryMessage` field most likely, it's meant for that, another option is replacing the `SentryException#value` but not sure about that.

`PlatformExceptions.code` can be either part of the`Contexts` somewhere or even the `SentryException#Mechanism`.

SDKs should not set tags by default (automatically), See [issue](https://github.com/getsentry/team-mobile/issues/60).
The solution would be adding somewhere and making it searchable/indexed in Sentry (if not yet), the issue above has more info.

Thanks for the suggestion.

**Comment by ueman** [comment]
Fair enough, any solution which makes that searchable would be an improvement

**Comment by marandaneto** [comment]
We can initially have event processors that enrich the event with the extra `PlatformException`, I believe the code should be under the `SentryException#Mechanism` because an event may have multiple exceptions (chained/inner).
Not sure if all the fields of `mechanism` are searchable, but we can make that happen separately on the sentry repo.

@ueman why do you need it to be searchable?
Are you filtering or alerting per specific codes? what's the reason behind it?
Usually, I'd go to events and look at the code in order to fix it faster, but I'd not filter per a specific code, just trying to understand your use case.

**Comment by ueman** [comment]
I would like to build a dashboard to see in which areas we have the most errors on the native side. I'd like to base that on the error code of the PlatformException because it's not really possible to do based on the `PlatformException.toString()`. There can be different messages for the same error code. This is more to see whether there are systematic issues, than to fix a specific error.

Also, since PlatformExceptions don't have any reference to the native code (only Android and JS can pass a stacktrace, but don't have to), you sometimes have to search native code based on the error code of the PlatformException.
