### ISSUE TITLE
debug symbols & obfuscation docs need improving

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry-dart#1281]
_Originally posted by @LeoRpc in https://github.com/getsentry/sentry-dart/issues/444#issuecomment-1426207169_
            
I cannot make it works guys :'(
But I tried my best: reading the docs, reading github issues, waiting **ton of time for my poor 2015 macbook pro to build my flutter app** to make tests... Soooo painful! Pleeeease help me :P

1- Inaccuracies I saw on the documentation
---
1. [Package documentation](https://pub.dev/packages/sentry_flutter): "Known limitations, Flutter split-debug-info and obfuscate flags aren't supported on iOS yet, but only on Android, if this feature is enabled, Dart stack traces are not human readable"
2. [Sentry docs for Flutter](https://docs.sentry.io/platforms/flutter/troubleshooting/#native-symbolication-on-iosmacos): "Flutter split-debug-info and obfuscate flags are supported on iOS/macOS."
3. [Sentry docs for Flutter](https://docs.sentry.io/platforms/flutter/upload-debug/#uploading-for-ios-and-macos): "... [Learn how to upload the dSYM files](https://docs.sentry.io/platforms/apple/dsym/)" send to the _native apple_ documentation, not the _flutter documentation_. [The corresponding flutter documentation](https://docs.sentry.io/platforms/flutter/upload-debug/#uploading-for-ios-and-macos) also point on the same _native apple_ documentation. **This could be OK, BUT**, as far as I know, the `flutter build ipa/ios --obfuscate --split-debug-info=$SPLIT_DEBUG_PATH` **does not outputs dSYM files** (as mentionned in the _native apple_ documentation), but .symbols files which adds to the confusion!

2- My issue
----
### Note
1. It works well for Android, but not for iOS.
2. I come from web development so I have no background on flutter or native development.
3. I use Flutter 3.7.2, sentry_flutter: ^6.19.0, flutter doctor all ok...

### Issue
1. `flutter build appbundle --obfuscate --split-debug-info=$SPLIT_DEBUG_PATH`
2. `sentry-cli difutil check $SPLIT_DEBUG_PATH/app.android-x64.symbols` (one random android .symbol file) outputs:
`Type: elf debug companion
  Contained debug identifiers:
    > Debug ID: 8e504493-5a69-af67-4c94-29828efc4ec9
      Code ID:  9344508e695a67af4c9429828efc4ec9
      Arch:     x86_64
  Contained debug information:
    > symtab, debug
  Usable: yes`
5. `flutter build ipa --obfuscate --split-debug-info=$SPLIT_DEBUG_PATH`
6. `sentry-cli difutil check $SPLIT_DEBUG_PATH/app.ios-arm64.symbols` (one random ios .symbol file) outputs:
`Type: elf debug companion
  Contained debug identifiers:
    > Debug ID: 00000000-0000-0000-0000-000000000000
      Arch:     arm64
  Contained debug information:
    > symtab, debug
  Usable: no (missing debug identifier, likely stripped)`
7. `flutter build **ios** --obfuscate --split-debug-info=$SPLIT_DEBUG_PATH` -> same result

### Question
Is there an issue with the way I build my flutter app (maybe the expected split-debug-info files are really dSYM files?)?
With Sentry? Sentry-cli?
Directions to investigate?

Thanks in advance! <3
Leo

**Comment by vaind** [comment]
@LeoRpc, Seems like docs do need updating (also Flutter docs maybe). 

With the latest Flutter, your build should have produced `*.dSYM` files in addition to ".symbols" (which are DWARF and as such useless for Sentry when handling iOS errors). Make sure you upload those to Sentry. You can see all the produced files, e.g. by finding them with sth like `ls -alh ./**/*.dSYM`

**Comment by LeoRpc** [comment]
Hi @vaind, thank you for your answer!

In fact, the `flutter build ipa --obfuscate --split-debug-info=$SPLIT_DEBUG_PATH` command generates some `.dSYM` files, but there are not located in the `$SPLIT_DEBUG_PATH` folder:
```
% ls -alh ./**/*.dSYM
./build/ios/archive/Runner.xcarchive/dSYMs/App.framework.dSYM:
total 0
drwxr-xr-x   3 leorapaic  staff    96B 13 fév 11:01 .
drwxr-xr-x  10 leorapaic  staff   320B 13 fév 11:02 ..
drwxr-xr-x   3 leorapaic  staff    96B 13 fév 11:01 Contents

./build/ios/archive/Runner.xcarchive/dSYMs/Runner.app.dSYM:
total 0
drwxr-xr-x   3 leorapaic  staff    96B 13 fév 11:02 .
drwxr-xr-x  10 leorapaic  staff   320B 13 fév 11:02 ..
drwxr-xr-x   4 leorapaic  staff   128B 13 fév 11:02 Contents

[...]
```

**It works** when I upload the files in the `dSYMs` folder 🎉.
**But** it seems very counter intuitive that the output specific to the `--obfuscate` and `--split-debug-info=$SPLIT_DEBUG_PATH` flags is not the one to feed into Sentry. The docs definitely needs some update (as well as Flutter docs I agree!), especially since it is a different process between iOs and Android.  

Summary
---
### Android
- Flutter: `flutter build appbundle/apk […] --obfuscate --split-debug-info=$SPLIT_DEBUG_PATH;` (with the `$SPLIT_DEBUG_PATH` **NOT BEING** in format `/<project-name>/<directory>` [despite the Flutter docs](https://docs.flutter.dev/deployment/obfuscate) - see [Flutter #74315](https://github.com/flutter/flutter/issues/74315))
- Sentry-cli: `sentry-cli upload-dif $SPLIT_DEBUG_PATH`
 
### iOs
- Flutter: `flutter build ipa/ios […] --obfuscate --split-debug-info=$SPLIT_DEBUG_PATH;` (with the `$SPLIT_DEBUG_PATH` **NOT BEING** in format `/<project-name>/<directory>` [despite the Flutter docs](https://docs.flutter.dev/deployment/obfuscate) - see [Flutter #74315](https://github.com/flutter/flutter/issues/74315))
- Sentry-cli: ``sentry-cli upload-dif build/ios/archive/Runner.xcarchive/dSYMs``

**Comment by marandaneto** [comment]
@LeoRpc thanks for raising this.
The recommended way is to use the [Sentry Dart Plugin](https://docs.sentry.io/platforms/flutter/upload-debug/#sentry-dart-plugin) which is now GA.
The plugin is aware of this issue and for iOS specifically, calls sentry-cli in the root folder (build) instead of the given `split-debug-info` folder.
As an example, [see](https://github.com/getsentry/sentry-dart/blob/main/flutter/example/run.sh) this script.

We'll ensure this is reflected in the docs when people use the other options (eg sentry-cli directly).

**Comment by 10000001a** [comment]
I have same problem with vaind.
`.DSYM` files were already uploaded well, but is there any way to upload ios .symbol file to sentry?

`sentry-cli dif check` says android .symbol files is usable but ios .symbol files are not usable.

**Comment by marandaneto** [comment]
@10000001a https://github.com/getsentry/sentry-docs/pull/6540

**Comment by 10000001a** [comment]
@marandaneto Thanks to answer.
You mean that `app.ios-arm64.symbols` file isn't neccessary to get readable stacktrace of sentry issue.
Do I understand correctly?

**Comment by marandaneto** [comment]
Yes, for iOS https://docs.sentry.io/platforms/flutter/upload-debug/#sentry-dart-plugin
Tracking the other docs improvements here https://github.com/getsentry/sentry-dart-plugin/issues/83
