### ISSUE TITLE
Make starting transactions from headers more convenient

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#1384]
### Problem Statement

It's currently quite cumbersome to start transactions from headers on the backend.
See the following example:
```dart
final request = ...
final urlDetails = HttpSanitizer.sanitizeUrl(request.url.toString());

var description = request.method.toString();

if (urlDetails != null) {
  description += ' ${urlDetails.urlOrFallback}';
}

final traceHeaderValue = request.headers['sentry-trace'];
final baggageHeaderValue = request.headers['baggage'];

SentryTransactionContext? trxContext;

if (traceHeaderValue != null) {
  trxContext = SentryTransactionContext.fromSentryTrace(
    description,
    'http.client',
    SentryTraceHeader.fromTraceHeader(traceHeaderValue),
    baggage: baggageHeaderValue != null
        ? SentryBaggage.fromHeader(baggageHeaderValue)
        : null,
  );
}

final trx = trxContext != null
  ? Sentry.startTransactionWithContext(trxContext, bindToScope: true)
  : Sentry.startTransaction(description, 'http.client', bindToScope: true);
```

### Solution Brainstorm

It would be very convenient if I can either create a `SentryTransactionContext` from headers, or start a transaction directly from headers with something like `Sentry.startTransactionFromHeaders`.

I recognize that it's probably tricky to choose what to except as cookies, since `dart:io`, `http` and `dio` use different formats for their headers.

### Are you willing to submit a PR?

None

**Comment by marandaneto** [comment]
Yeah I agree the problem is that every framework has a different datatype for `headers`, the best we can do here is to offer first support for the framework you are working with, for example `dart_frog`, so that we automatically instrument everything by default, you don't really have to do anything.
What we can do here is to make a factory for `SentryTraceHeader.fromHeadersMap(...)` that takes a `Map<String, Object?>` and try to extract the headers we know by default at least, it helps a bit with the boilerplate.
Would that help?
We cannot automatically make the `desc` for every framework, since each framework has its own type for `request`, etc.

**Comment by marandaneto** [comment]
@ueman would the helper `SentryTraceHeader.fromHeadersMap(...)` helps or would you rather close this in preference over first-class support of your library (dart_frog) I believe?

**Comment by ueman** [comment]
I guess support through first-class support of dart_frog should be sufficient, since there's not many other web frameworks in the Dart world. serverpod and shelf are other ones, but I'm not really aware of their popularity.

**Comment by marandaneto** [comment]
Closed in favor of https://github.com/getsentry/sentry-dart/issues/1389
