### ISSUE TITLE
Severe logs should be included as breadcrumbs for other events

### ISSUE THREAD

**Issue by maBarabas** [getsentry/sentry-dart#1583]
### Problem Statement

I have multiple errors happening in the app as a result of a bug. These are triggering multiple severe logs and uncaught exceptions. When looking at the events through Sentry, the severe logs are not present in the breadcrumbs for the event related to the uncaught exception.

The code looks something like this:

```
try {
   resource = createResource();   
} except (e) {
  log.severe('bug');
  resource.cleanup();
 rethrow;
}
```

The rethrow is never caught, and the event for the uncaught exception does not include the `bug` log as a breadcrumb. This made me assume that this is not the branch that failed. I only realised what's going on after adding random throws around the code and comparing the Sentry logs between the original event and my modified version.

### Solution Brainstorm

When sentry submits an event, previous events from the same sessions should be included as breadcrumbs.

### Are you willing to submit a PR?

Yes

**Comment by krystofwoldrich** [comment]
Hi,
thank you for the message, this looks like a bug.

The `logger.sever` creates a breadcrumb and event, the breadcrumb should be included in the event created from the rethrown exceptions. At the moment I don't see why it's not included. We will investigate it.

Because the breadcrumbs from the logger are created asynchronously:

https://github.com/getsentry/sentry-dart/blob/d78342459141e1798a213da74ad13e89235cbe31/logging/lib/src/logging_integration.dart#L54-L55

https://github.com/getsentry/sentry-dart/blob/d78342459141e1798a213da74ad13e89235cbe31/logging/lib/src/logging_integration.dart#L66-L69

The rethrown error is processed before the logger breadcrumb is created.

**Comment by ueman** [comment]
> Hi, thank you for the message, this looks like a bug.
> 
> The `logger.sever` creates a breadcrumb and event, the breadcrumb should be included in the event created from the rethrown exceptions. At the moment I don't see why it's not included. We will investigate it.

I have hunch, that the different ways of serialization for whole events vs serialization for the native sync is the issue.
When doing serialization for whole events, it's done via https://github.com/getsentry/sentry-dart/blob/d78342459141e1798a213da74ad13e89235cbe31/dart/lib/src/utils.dart#L31
but for the native sync there's nothing like that
https://github.com/getsentry/sentry-dart/blob/d78342459141e1798a213da74ad13e89235cbe31/flutter/lib/src/sentry_native_channel.dart#L59 
thus when non-serializable objects are added to a breadcrumb it just fails.

**Comment by krystofwoldrich** [comment]
@ueman I think you are talking about this issue -> https://github.com/getsentry/sentry-dart/issues/1581

This here is about the breadcrumb missing (even with just a string log -> serialization will work).

**Comment by marandaneto** [comment]
@maBarabas can you share your SDK init code snippet?
Also, a minimal reproducible example would help unless you are swallowing your exceptions, every unhandled exception should be captured automatically, and the previous errors should be part of breadcrumbs, as long as they were within the same session.

Last question, which library/package are you using for `log.severe('bug');`?

**Comment by krystofwoldrich** [comment]
@marandaneto I was able to reproduce the issue with this code, [adjusted the `tryCatch` function from our example app](https://github.com/getsentry/sentry-dart/blob/d78342459141e1798a213da74ad13e89235cbe31/flutter/example/lib/main.dart#L529).

```dart
Future<void> tryCatch() async {
  try {
    throw StateError('try catch');
  } catch (error, stackTrace) {
    Logger("test").severe('bug');
    // await Sentry.captureException(error, stackTrace: stackTrace);
    rethrow;
  }
}
```

**Comment by maBarabas** [comment]
@marandaneto, here is my init:

```
Future<void> main() async {
  // Work around sentry not printing these errors for now. I've created a PR
  // that adds logging support. We can delete this after that's merged.
  // https://github.com/getsentry/sentry-dart/pull/1257
  PlatformDispatcher.instance.onError = (e, s) {
    return false;
  };

  // Make sure that severe and above logs have a stack trace for good grouping
  // in sentry. If there is no stack, then all the different log lines are
  // grouped together by default. We have worked around that by setting up a
  // grouping rule to split those groups by the messages.
  recordStackTraceAtLevel = Level.SEVERE;
  await SentryFlutter.init(
    (options) {
      options
        ..dsn = sentryDsn
        // enable debug logging for local development use cases, disable for
        // production
        ..debug = kDebugMode || kProfileMode
        ..diagnosticLevel = SentryLevel.info
        ..addIntegration(LoggingIntegration())
        // The app does all of its logging trough the logging package. We also
        // log to the console for debugging. Disable breadcrumbs for the console,
        // so that we don't see duplicate breadcrumbs in Sentry.
        //
        // Temporary fix: https://monitoraudio.atlassian.net/browse/MUF-264
        //
        // Sentry is missing error level logs in breadcrumbs for other related
        // events: https://github.com/getsentry/sentry-dart/issues/1583
        //
        // Every log is printed to the console, so this works around the issue.
        ..enablePrintBreadcrumbs = true
        // Set tracesSampleRate to 1.0 to capture 100% of transactions for performance monitoring.
        // We recommend adjusting this value in production.
        ..tracesSampleRate = 1.0
        ..attachScreenshot = true;
    },
    appRunner: appMain,
  );
}
```

Logging is done with [package:logging](https://pub.dev/packages/logging) so that I can make use of the `LoggingIntegration`.

The default log level is set to `INFO`.

I also use `SentryUserInteractionWidget` and `SentryScreenshotWidget` at the root of the app's widget tree.

I think the setup proposed by Kryštof should be representative.

**Comment by marandaneto** [comment]
Ok, I see, the problem is that `Logger.root.onRecord.listen` takes a `void onData(T event)?` function but it does not `await` the function call, so its added to the event loop since Sentry's callback is a `Future`.

The `Logger("test").severe('bug');` call captures a new event and breadcrumb, but due to the event loop, the crumb is added a bit after the `rethrow` event is also captured.

In both cases, I see both events captured in the sentry.io dashboard though.

<img width="469" alt="Screenshot 2023-08-07 at 14 03 28" src="https://github.com/getsentry/sentry-dart/assets/5731772/9105dcaa-2349-43f4-aee6-211d6ca9be8d">

The `StateError` error does not contain the `bug` breadcrumb, but it should.

Since we don't have control over the `logging` API, we cannot change this behavior but rather make it as best effort, this only happens when creating the crumb and an error happens very next to each other, right?

**Comment by marandaneto** [comment]
Similar issue https://stackoverflow.com/questions/75752421/flutter-run-async-function-on-stream-listen

`onRecord` is a `get` so I cannot overwrite and combine with `asyncMap` or something else.

@maBarabas or @ueman do you have any ideas on how to fix this?

**Comment by krystofwoldrich** [comment]
As we don't have [control over the Logger implementation](https://github.com/getsentry/sentry-dart/issues/1583#issuecomment-1667731428) the workaround is to create a custom breadcrumb that will be awaited and therefore created before the rethrow.

```dart
Future<void> tryCatch() async {
  try {
    throw StateError('try catch');
  } catch (error, stackTrace) {
    Logger("test").severe('bug');
    await Sentry.addBreadcrumb(
      Breadcrumb(
        message: 'bug',
      ),
    );
    rethrow;
  }
}
```
