### ISSUE TITLE
Obfuscated built Flutter app obfuscates Sentry message

### ISSUE THREAD

**Issue by b4tchkn** [getsentry/sentry-dart#1663]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Obfuscate Flutter apps with using `--obfuscate --split-debug-info=./` options.
2. Upload symbol files to Sentry using `sentry-cli debug-files upload -o <org> -p <project> ./` on  CI.
3. Send class runtimeType or StackTrace.current() to SentryEvent message in Flutter.
4. Check Issues on Sentry.

### Expected Result

To be confirmed messages that have not been obfuscated.

### Actual Result

The message arrives on Sentry obfuscated.

So, If I don't set stackTrace when call `Sentry.captureEvent()`, StackTrace on Sentry will be unknown. before Flutter obfuscation, I could see a normal StackTrace.
If I set stackTrace to StackTrace.current, etc. when call `Sentry.captureEvent()`, I can confirm a normal StackTrace.

Is it a specification that obfuscation occurs when source code objects are included in the message and that StackTrace is obfuscated when StackTrace is not specified?

### Product Area

Issues

**Comment by stefanosiano** [comment]
hey @b4tchkn Could you please provide us a link to the event?
If you don't want to provide a link on this github issue, you can send it via email to stefano.siano@sentry.io
Also, are you experiencing it on a specific platform, like web?

**Comment by b4tchkn** [comment]
@stefanosiano 
This is occurring on iOS and Android.
And sent an email with a link to the Sentry event. Please check it out.

**Comment by stefanosiano** [comment]
hey @b4tchkn 
I had a look at the event, and it seems like it's related to https://github.com/getsentry/sentry-dart/issues/1565 and https://github.com/getsentry/sentry-dart/issues/2805
I'll have a closer look and come later. As pointed in https://github.com/getsentry/sentry-dart/issues/2805, though, it's quite a big scope

**Comment by stefanosiano** [comment]
hey @b4tchkn 
after merging https://github.com/getsentry/sentry-dart/pull/1756, the stacktraces of the events captured with `captureMessage` or `captureEvent` will be deobfuscated. Note that you either have to put your own stacktrace or use the `await` keyword when calling Sentry APIs to get the calling function in the stacktrace, due to technical limitations.
Regarding deobsfuscation of messages, that's a bigger topic that we are discussing internally.

I'm closing this issue for now. Feel free to add a comment in case the fix doesn't work for your case
