### ISSUE TITLE
Handling of package errors

### ISSUE THREAD

**Issue by Mounix99** [getsentry/sentry-dart#1782]
### Platform

Dart

### Obfuscation

Enabled

### Debug Info

Enabled

### Doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.9, on macOS 14.1.2 23B92 darwin-arm64, locale en-UA)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!

### Version

7.13.2

### Steps to Reproduce

In my project reportPackages set as false. But I get errors related to syncfusion calendar package to sentry console 

### Expected Result

Do not receive errors related to packages

### Actual Result

A huge amount of package errors shown

### Are you willing to submit a PR?

No

**Comment by buenaflor** [comment]
Hi

is only syncfusion calendar affected by this? also which platforms are you working with? (android, ios, web)

**Comment by ueman** [comment]
The `reportPackages` does toggle whether package names are added to an event. Not whether exceptions from third party code is send to Sentry

**Comment by Mounix99** [comment]
@buenaflor Hi, 
I'm working with android, iOS and Web. After enabling this option I noticed errors from syncfusion packages and from stream_chat packages (especially connections errors through there WebSockets)

**Comment by buenaflor** [comment]
Seems like the doc for the `reportPackage` is misleading.

@Mounix99 can you share a link to one of these errors? You can also send them at giancarlo.buenaflor@sentry.io if you're uncomfortable here. I'd assume they are related to our flutter error integration that catches and sends unhandled errors.

**Comment by Mounix99** [comment]
@buenaflor Sure, have sended them to your email address

**Comment by buenaflor** [comment]
@Mounix99 

these errors were captured by our error [integration](https://github.com/getsentry/sentry-dart/blob/main/flutter/lib/src/integrations/flutter_error_integration.dart) which captures unhandled errors that bubbled up in `FlutterError.onError`. (that includes 3rd party packages, the flutter framework etc...)

In order to filter these we have limited options:
 - use [inbound filters](https://docs.sentry.io/product/data-management-settings/filtering/), custom filtering is unfortunately only available for business plans and above
 - disable the integration - the downside here is that you also won't capture unhandled errors that happened in your application, not only 3rd party
 ```dart
final errorIntegration = options.integrations.firstWhere(
    (element) => element.toString().contains('FlutterErrorIntegration'));
options.removeIntegration(errorIntegration);
```
- wrap calls of your 3rd party code in try/catch and don't do anything with the captured error.

The main problem is that we cannot differentiate between inApp frames or not with obfuscated stacktraces, at least not on the SDK level.

**Comment by buenaflor** [comment]
@Swatinem

hey, flutter has a global error handler that catches all unhandled errors and our SDK automatically captures those (including errors from outside the app). Afaik we cannot filter these on the SDK level due to obfuscated stacktraces. Are there any other options for filtering those on release builds besides using `inbound filters` or just disabling the integration?

**Comment by Swatinem** [comment]
I’m not quite sure if inbound filters are running before or after symbolication. Custom grouping rules run afterwards, thats for sure.

**Comment by buenaflor** [comment]
@Mounix99 seems like we are really limited in what we can do here. Besides what I've described in my comment there's not much we can do
