### ISSUE TITLE
Upgrade Package_info_plus to version 6

### ISSUE THREAD

**Issue by Bilonik** [getsentry/sentry-dart#1944]
### Description

sentry_flutter 7.18.0 depends on package_info_plus >=1.0.0 <=5.0.1

**Comment by kuhnroyal** [comment]
Judging from the [changelog](https://pub.dev/packages/package_info_plus/changelog#600), there are no changes to API. Only SDK constraints and WASM support, so this should theoretically just work with an override.

**Comment by kahest** [comment]
Hey, thanks for bringing this to our attention, we'll take a look

**Comment by denrase** [comment]
Just checked the [Changelog](https://pub.dev/packages/package_info_plus/changelog#600) , where version 6.0.0 depends upon:

| Dependency | Current Version | New Version |
| ------------ | ---------------- | ------------- |
| Flutter  | >= 3.0.0 | >=3.19.0 |
| Dart  | >= 2.17.0 | >=3.3.0 |
| macOS  | 10.13 | 10.14 |
| Android Target SDK | 33 | 34 |
| Android Java | VERSION_1_8 | VERSION_17 |
| Android Gradle | 7.2.2 | 8.4 |

Since the version is provided as a range, we probably don't have to upgrade all of them, as the dependency resolution will find compatible versions when we provide a range.

**Comment by kuhnroyal** [comment]
> Just checked the [Changelog](https://pub.dev/packages/package_info_plus/changelog#600) , where version 6.0.0 depends upon:
> 
> Dependency	Current Version	New Version
> Flutter	>= 3.0.0	>=3.19.0
> Dart	>= 2.17.0	>=3.3.0
> macOS	10.13	10.14
> Android Target SDK	33	34
> Android Java	VERSION_1_8	VERSION_17
> Android Gradle	7.2.2	8.4
> Since the version is provided as a range, we probably don't have to upgrade all of them, as the dependency resolution will find compatible versions when we provide a range.

This should not matter, this is the responsibility of the implementor.
Increasing the range just would allow this.
