### ISSUE TITLE
IO platforms should read dart defines to configure Sentry

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#2216]
### Problem Statement

On web, Sentry reads the configuration from dart defines, this should be done on dart:io platforms too.
The environment variables are only available on desktop platforms, but not on mobile, but we can use dart defines on mobile.

Ref https://github.com/getsentry/sentry-dart/blob/384a55ca441aaa03965659ad70daede0f91fa351/dart/lib/src/environment/_web_environment_variables.dart

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
yeah makes sense 👍

**Comment by martinhaintz** [comment]
[`IoEnvironmentVariables`](https://github.com/getsentry/sentry-dart/blob/main/dart/lib/src/environment/_io_environment_variables.dart) already extends the [`WebEnvironmentVariables`](https://github.com/getsentry/sentry-dart/blob/main/dart/lib/src/environment/_web_environment_variables.dart) and the `WebEnvironmentVariables` is called via `super` before the `Platform.environment`. 
See `String? get environment =>
      super.environment ?? Platform.environment[sentryEnvironment];`

In addition, conditional imports of libraries can only distinguish between `WEB` and `IO`. `IO` includes `Desktop` and `Mobile`.

I also tested it using these settings in Android Studio and `definebar` is used instead of `envbar`
![Image](https://github.com/user-attachments/assets/b95e05cc-a908-4d6a-b809-bb11a5474565)

To me, it looks like this is already working.

@ueman if this is not the case, can you please elaborate in more detail on what you mean?
