### ISSUE TITLE
Plan to drop old Flutter version

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dart#2281]
### Description

Is there a plan?

I see we lose pub points due to lack of wasm support: https://pub.dev/packages/sentry_flutter/score
We need symbolication for wasm it seems.

But we do support it otherwise. Through some hacks needed to have backward compatibiltiy.
Is there a plan to drop it?

**Comment by buenaflor** [comment]
We support wasm, at least compilation, but lose pub points due to the workaround for backwards compatibility, yes

There was demand from the google flutter web team to support it on our side since some customers rely on it. I think that's a fair trade for losing some pub points.

I might take a stab at symbolication, at least a quick look to check the effort.

Fully supporting wasm with full pub points though won't be possible in the near future since the new package (package:web) uses a ~2 month old dart version which is way too new.

so dropping an older flutter version in favour of a newer one won't help us in this situation, maybe in 1 or 2 years it would

**Comment by bruno-garcia** [comment]
Also note that .NET and Unity also support wasm.
Perhaps makes sense for us to collaborate on wasm support when the time comes to invest more heavily

**Comment by buenaflor** [comment]
I've already opened an issue in the dart repo

https://github.com/dart-lang/sdk/issues/56718 this will unblock us
