### ISSUE TITLE
Not showing error message in sentry

### ISSUE THREAD

**Issue by Maruf-Elsa** [getsentry/sentry-dart#2423]
### Platform

Flutter Mobile

### Obfuscation

Enabled

### Debug Info

Enabled

### Doctor

```terminal
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.1.2 23B92 darwin-arm64, locale en-IN)
    • Flutter version 3.24.0 on channel stable at /Users/marufhassan/fvm/versions/3.24.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 80c2e84975 (4 months ago), 2024-07-30 23:06:49 +0700
    • Engine revision b8800d88be
    • Dart version 3.5.0
    • DevTools version 2.37.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/marufhassan/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/marufhassan/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.95.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.100.0

[✓] Connected device (4 available)            
    • sdk gphone64 arm64 (mobile)     • emulator-5554         • android-arm64  • Android 15 (API 35) (emulator)
    • macOS (desktop)                 • macos                 • darwin-arm64   • macOS 14.1.2 23B92 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS 14.1.2 23B92 darwin-arm64
    • Chrome (web)                    • chrome                • web-javascript • Google Chrome 131.0.6778.70

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### Version

8.9.0

### Steps to Reproduce

1. Created a function to hit logs for Sentry in a gesturedetector button.
```dart
                      LoggerManager().log(
                        LogLevel.error,
                        'Login_Failure2',
                        metadata: {
                          'logger_message':'Missing Token',
                          'setTagKey': AuthenticationChannelKeys.loggerMessage,
                          'setTagValue': 'Google Login',
                        },
                      );
```

```dart
import 'package:sentry_flutter/sentry_flutter.dart';

import 'logger.dart';

class SentryLogger implements Logger {
  @override
  void log(LogLevel level, String message, {Map<String, dynamic>? metadata}) {
    List<dynamic>? params;
    var sentryLevel = SentryLevel.info;

    switch (level) {
      case LogLevel.debug:
      case LogLevel.info:
        sentryLevel = SentryLevel.info;
        params = metadata?.values.toList();

      case LogLevel.warn:
        sentryLevel = SentryLevel.warning;

      case LogLevel.error:
        sentryLevel = SentryLevel.error;
    }

    Sentry.captureMessage(
      message,
      level: sentryLevel,
      params: params,
      withScope: (scope) {
        if (metadata != null) {
          metadata.forEach((key, value) {
            scope.setContexts(key, value);
          });
        }
      },
    );

    if (level == LogLevel.error &&
        metadata != null &&
        metadata.containsKey('exception')) {
      Sentry.captureException(metadata['exception']);
    } else if (level == LogLevel.error &&
        metadata != null &&
        metadata.containsKey('logger_message')) {
      Sentry.configureScope((scope) {
        if (metadata.containsKey('setTagKey') &&
            metadata.containsKey('setTagValue')) {
          scope.setTag(
            metadata['setTagKey'] as String,
            metadata['setTagValue'] as String,
          );
        }
      });
      Sentry.captureException(
        stackTrace: message,
        metadata['logger_message'],
      );
    }
  }

  @override
  void debug(String message, {Map<String, dynamic>? metadata}) =>
      log(LogLevel.debug, message, metadata: metadata);

  @override
  void info(String message, {Map<String, dynamic>? metadata}) =>
      log(LogLevel.info, message, metadata: metadata);

  @override
  void warn(String message, {Map<String, dynamic>? metadata}) =>
      log(LogLevel.warn, message, metadata: metadata);

  @override
  void error(String message, {Map<String, dynamic>? metadata}) =>
      log(LogLevel.error, message, metadata: metadata);
}

```
2. After successful trigger we get the setTagKey & setTagValue in Sentry but for **logger_message** metadata we don't get the error message 'Missing Token' we get value as **[Filtered]** as shown in this pic - https://imgur.com/Yavd4lG
3. In the Issues page we see another event created called with the error message **Missing Token** but for the event **Login_Failure2** we don't get any error message **(No error message)**. I have added the pic - https://imgur.com/7Q4nTaH

```
String 
unparsed in Login_Failure2
```

### Expected Result

My expected result was seeing the event in Sentry with the error message 'Missing Token' instead of **No error message** - https://imgur.com/aM3XMpu

### Actual Result

I am getting two different events, I want to recieve only 1 event - https://imgur.com/7Q4nTaH

### Are you willing to submit a PR?

None

**Comment by buenaflor** [comment]
hey thank you for the issue, we'll have a look. is this an issue on both iOS and Android?

**Comment by Maruf-Elsa** [comment]
Its happening in both Android and iOS @buenaflor

**Comment by Maruf-Elsa** [comment]
Its on both Android & iOS

**Comment by buenaflor** [comment]
thank you we'll have a look

**Comment by martinhaintz** [comment]
Hello @Maruf-Elsa,

The sentry backend, automatically scrubbes the data all events by default to make sure no PII, credentials like passwords etc. are stored and visible in Sentry. This also includes strings containing the keyword [`token`](https://docs.sentry.io/security-legal-pii/scrubbing/server-side-scrubbing/). **_It looks like the docs are not up to date, and are missing the `token` keyword here. I will update the docs as soon as possible._**
Based on your code the value `Missing Token` contains the keyword `token` and will then be displayed as `[Filtered]`.
I recommend to add `logger_message.value` as `Safe Fields` in your Sentry Settings:
![Image](https://github.com/user-attachments/assets/8c35d60f-d633-4bdd-9c72-321e7cde0183)
This will disable the scrubbing for the `logger_message` field. 
Please wait 1-2 minutes, after adding this field, because it takes some time until the backend services are all synced with your changes.
**_Please make sure, that there will be no PII, actual tokens, or other credentials written in this field. As this field is now excluded from scrubbing and the data is stored and visible via sentry._**

You can find a detailed explanation about the data scrubbing [here](https://docs.sentry.io/security-legal-pii/scrubbing/).

Regarding the `(No error message)` in Sentry you need to set the `scope.transaction` with your `message` variable.
Here is a short example of how to achieve this:
![Image](https://github.com/user-attachments/assets/c6a96a23-6831-4964-8cc7-b95b14cfbb32)
Here is the code:
```dart
Sentry.captureMessage(
  "this is the `message`",
  level: SentryLevel.error,
  withScope: (scope) {
    scope.transaction = "this is the `scope.transaction`";
  },
);
```

Regarding your duplicated entries in Sentry, I saw, that you are sending two events to Sentry. The first is via `Sentry.captureMessage` and the second is via `Sentry.captureException` therefore you see two `issues` in sentry.

The `String unparsed in Login_Failure2` is coming from the `Sentry.captureException` call, because you are calling:
```
Sentry.captureException(
  stackTrace: message,
  metadata['logger_message'],
);
```
and assigning `stackTrace` with the type `String` instead of `StackTrace`. The `String unparsed in Login_Failure2` is the error of the backend failing to read the `stackTrace` as it is the wrong format and expecting a `StackTrace` object and not a `String`.

I hope this helps.

BR Martin

**Comment by kahest** [comment]
closing as solved - pls reply if you have more questions or problems
