### ISSUE TITLE
Windows ARM64 Build failing

### ISSUE THREAD

**Issue by nowfalsalahudeen** [getsentry/sentry-dart#2498]
### Platform

Flutter Desktop Windows

### Obfuscation

Disabled

### Debug Info

Disabled

### Doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.27.0, on Microsoft Windows [Version 10.0.22621.4169], locale en-US)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✗] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.12.3)
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.95.2)
[✓] Connected device (2 available)
[✓] Network resources

! Doctor found issues in 1 category.

### Version

8.11.0

### Steps to Reproduce

C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\BuildCustomizations\marmasm.targets(56,5): error MSB8076: Only ARM, ARM64 and ARM64EC platforms are supported. [C:\Users\nowfal\VaasITS\edr-pos-userapp-flutter\build\windows\x64\_deps\sentry-native-build\crashpad_build\util\crashpad_util.vcxproj]
Building Windows application...                                    25.0s
Build process failed.

Macbook m2 Pro with parallel desktop windows 11 arm64

### Expected Result

It was working fine , after upgrade the sdk, got this error,

### Actual Result

C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\BuildCustomizations\marmasm.targets(56,5): error MSB8076: Only ARM, ARM64 and ARM64EC platforms are supported. [C:\Users\nowfal\VaasITS\edr-pos-userapp-flutter\build\windows\x64\_deps\sentry-native-build\crashpad_build\util\crashpad_util.vcxproj]
Building Windows application...                                    25.0s
Build process failed.

### Are you willing to submit a PR?

None

**Comment by vaind** [comment]
v8.11 brought Windows native error & obfuscation support (https://github.com/getsentry/sentry-dart/pull/2286, https://github.com/getsentry/sentry-dart/pull/2426)

It seems like you're building ARM64 but it doesn't get propagated and something actually builds as x64. 

Can you update the `Steps to reproduce` to include the build command you're using?

Also, it seems like sentry-native currently doesn't support Windows ARM64, see https://github.com/getsentry/sentry-native/issues/880 - we may need to make adjustment here to exclude the cmake target in this case.

**Comment by Ali-Toosi** [comment]
Same issue here. The same setup as [nowfalsalahudeen](https://github.com/nowfalsalahudeen). The command is just Flutter's debug or build command:
```
flutter run
```

I'm not sure if it's an 8.11.0 issue or a general one though. Because downgrading Sentry did not fix the issue. But I can confirm removing Sentry from the project does fix the issue and the build starts working again.

EDIT: my bad, downgrading to 8.10.0 does fix the problem. The issue is only present in 8.11.

**Comment by buenaflor** [comment]
@Ali-Toosi which versions did you downgrade to where it still doesnt work?

**Comment by Ali-Toosi** [comment]
@buenaflor Actually sorry it does work with 8.10.0. I thought I had downgraded but I hadn't. 8.10.0 runs, 8.11.0 and 8.11.1 don't.
Let me know if you'd like me to try another version.

**Comment by buenaflor** [comment]
Thanks, we added a feature in 8.11.0 that is enabled by default but due to the impact it has on build fails on linux and windows we will make the feature opt-in for now (until the next major - 9)

**Comment by Ali-Toosi** [comment]
Thank you! 8.11.2 working.

**Comment by vaind** [comment]
Just released v8.11.2 disabled the native crash reporting by default. If you'd like to try it out and provide feedback (since Windows Arm64 is not very common, the feedbeck would be very valuable), you can try enabling a crash handling backend by setting an env var:

(the following code is for powershell, assuming that's what you use on Windows)
```pwsh
$env:SENTRY_NATIVE_BACKEND = 'breakpad'
flutter build windows
```

You could read about various backends in https://docs.sentry.io/platforms/native/advanced-usage/backend-tradeoffs/ but TLDR is that `crashpad` is preferrable unless you cannot use it, e.g. because you cannot ship an additional executable along your app, or like in this case, it doesn't work for the platform you're building for (yet). If that's the case, there's `breakpad` and `inproc`, which both run in the same process have some advantages over each other. If you don't care about these (they're described in docs), `breakpad` would be the next best thing after `crashpad`.

**Comment by vaind** [comment]
One more note: in sentry_flutter v9, we're likely to enable native crash reporting again, with `breakpad` as default for ARM64 unless we can make `crashpad` work.

**Comment by lukemmtt** [comment]
I'm getting this error with Sentry 9.5.0. Same environment as OP.

Running the command `$env:SENTRY_NATIVE_BACKEND = 'breakpad'` prior to building resolves the issue (thank you @vaind!), but from the recent explanation, I got the impression that this shouldn't have been needed at this point.

Is this expected at this time? Glad to create a new issue if desired. Thank you!

**Comment by buenaflor** [comment]
@lukemmtt did you test this on Windows ARM64 only?

breakpad should be the default for Windows ARM64 unless we messed something up

**Comment by lukemmtt** [comment]
Indeed, Windows ARM64 running in Parallels on Mac. Did `flutter clean` and everything else I could think of too. I can probably repro it easily if you need.

**Comment by vaind** [comment]
We check `FLUTTER_TARGET_PLATFORM` - you can try printing that in CMake do see if it matches [what we expect](https://github.com/getsentry/sentry-dart/blob/3615e19973d040cd9c8177ed7579c0d91d7e1eaa/flutter/windows/CMakeLists.txt#L7C4-L7C27) in the plugin.

**Comment by BrainRayChristensen** [comment]
@vaind I'm running Windows ARM64 in VMware Fusion on Mac. Adding `message("FLUTTER_TARGET_PLATFORM: ${FLUTTER_TARGET_PLATFORM}")` to my `CMakeLists.txt` prints out `FLUTTER_TARGET_PLATFORM: windows-x64`. I looked into it a little bit, and it seems like that is always the target platform, regardless of what platform you are running flutter from
