### ISSUE TITLE
`close` should to disable completely the SDK

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dart#291]
Pass the call to Android and iOS to ensure all layers get closed.

Depends on: 
https://github.com/getsentry/sentry-java/issues/1225
https://github.com/getsentry/sentry-cocoa/issues/934

The behavior should be that calling `Sentry.close()` will block the caller until all events queued up to the point of `close` being called are flushed out. And then the SDK can be closed and the method returns.

If it's simpler to implement it in a way that it'll keep waiting for events to be flushed even if those were queued after `close` was called, that's fine but essentially that would mean that if you have `capture` in a tight loop, it'll always stop only upon timeout.

The behavior above is describing `flush` which is an optional API here but is part of the behavior of `close`. 

Example of such implementation: https://github.com/getsentry/sentry-dotnet/blob/2337261333d5743996d6d96ca3aa289d34a9d3ec/src/Sentry/Internal/BackgroundWorker.cs#L182-L261

This will unblock the issue #352 since the user can call `Sentry.close()` to make sure events are not lost, before exiting the app.

**Comment by marandaneto** [comment]
@ueman maybe let's create a new one which is only about using the latest Cocoa once is GA, so we could remove the enabled boolean with the proper method call, otherwise, we might forget :)

the issue title could be like Bump Cocoa SDK to v7 and then specifying what else we have to do, calling `close` instead fiddling with the `enabled` flag
