### ISSUE TITLE
Read `SENTRY_RELEASE` and other env vars in the `dart` package

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-dart#306]
Discovering release via env var is also useful in the core `dart` package to be used by Dart VM projects.

**Comment by marandaneto** [comment]
@ueman this issue is about https://github.com/getsentry/sentry-dart/blob/fecf4599fa2eb97d03fc4ef9fee765f3ecb23278/flutter/lib/src/default_integrations.dart#L362-L369
ideally, for non Android/iOS, this should work for the Dart package too, maybe moving this around

https://github.com/getsentry/sentry-dart/blob/main/dart/lib/src/sentry.dart#L64-L72

**Comment by ueman** [comment]
Thanks, I already figured that out, though.

One question I have is the order of precedence.
Is it `environment variables` over `SentryOptions` over `values read from package_info or device`?

**Comment by marandaneto** [comment]
see here https://docs.sentry.io/platforms/dart/configuration/options/

it depends on the property tbh, eg
options.dsn has precedence over SENTRY_DSN

SENTRY_ENVIRONMENT has precedence over options.environment

package_info has precedence over SENTRY_RELEASE, SENTRY_RELEASE has precedence over options.release (this is tricky as package_info is an integration and executed only later)

`dist` isn't documented but I guess it'd be similar to `environment`
