### ISSUE TITLE
Set SentryOptions.debug automatically reading from options.platformChecker.isDebugMode

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart#307]
If on Sentry.init, `SentryOptions.debug` is disabled, let's read from `options.platformChecker.isDebugMode` and if returning true, enabling debug mode, right now we only do it for sentry_flutter package reading from `kDebugMode`

**Comment by bruno-garcia** [comment]
I'm not sure we should set the Sentry SDK debug=true automatically based on the the project running on debug mode. We can be creating too much debug data that the user isn't interested to see and it'll make them opt-out.

**Comment by marandaneto** [comment]
we already do for Flutter, I kinda agree with you but no complaints so far, another way of looking into this would be, enable `debug` by default if it's a debug env. but default the min. level would be `error` so it's only noisy if necessary.

flutter itself has `debug` enabled by default btw.

**Comment by bruno-garcia** [comment]
That's nice but has the downside of the generic Sentry approach of "Please set debug=true and give us logs" won't work since it'll already be true, but the diag level will be set to error.

I'd say it's fine then to keep `debug=true` if that makes sense here but an obvious way to opt-out is needed (if user sets debug=false in the `init` callback for example it should take presedence.

**Comment by marandaneto** [comment]
this surely run before the user's callback, obviously, like we do with Flutter already, the idea was just to extend to Dart

**Comment by marandaneto** [comment]
the idea is to do this https://github.com/getsentry/sentry-dart/blob/main/flutter/lib/src/sentry_flutter.dart#L63 on the Dart package too as its cross-platform, maybe around https://github.com/getsentry/sentry-dart/blob/main/dart/lib/src/sentry.dart#L54
