### ISSUE TITLE
Impore error message: flutter: [error] Error in the 'configureScope' callback.

### ISSUE THREAD

**Issue by HazAT** [getsentry/sentry-dart#320]
When debugging an app I am calling:

```
Sentry.configureScope((scope) => scope.user = User(email: action.me.email));
```

which results in this log message: `flutter: [error] Error in the 'configureScope' callback.`

Is it possible to be more verbose here in debug and show the actual error: 

`'package:sentry/src/protocol/user.dart': Failed assertion: line 35 pos 16: 'id != null || ipAddress != null': is not true.`

So the solution is: 

```
Sentry.configureScope((scope) => scope.user = User(email: action.me.email, id: action.me.id, ipAddress: "{{auto}}"));
```

But the debug experience is not great.

**Comment by bruno-garcia** [comment]
PR welcome :trollface:

**Comment by marandaneto** [comment]
this is just on debug time, it won't throw on release mode, we can't force nullability because only one field is required, hence every field should be nullable.
https://develop.sentry.dev/sdk/event-payloads/user/

`assert` takes a `message` as reason, we could start using this way more or using default values, which would make sense for `ipAddress`
https://www.codevscolor.com/dart-assert-statement
but...

`{{auto}}` can only be used if `sendDefaultPii` is enabled, so we can't use default values either see #275

**Comment by ueman** [comment]
I think what @HazAT wants is that https://github.com/getsentry/sentry-dart/blob/64f5676299038f069c01a695a09bd2308ab382e0/dart/lib/src/hub.dart#L309 should print the exception message itself. Thus the user would know which exception was thrown. The generic error message isn't really helpful.

An assertion message would not have helped because it wouldn't be printed to console.

**Comment by HazAT** [comment]
exactly what @ueman said

**Comment by marandaneto** [comment]
oh yeah it makes sense, it was an oversight, see Java:

https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/Hub.java#L469

we always concatenate the error message
