### ISSUE TITLE
Migrate Client to HttpClient to offer the proxy setup

### ISSUE THREAD

**Issue by onewilk** [getsentry/sentry-dart#392]
In some case, developers need to config httpClient proxy settings to request the public network cause  company's network security requirement.

**So here is the problem:**

``` dart
sentry_options.dart

set httpClient(Client httpClient) => _httpClient = httpClient ?? _httpClient;
```
Client is an abstract class from the [http](https://pub.flutter-io.cn/packages/http) lib, and it doesn't offer the proxy setup yet.

Please migrate Client to [HttpClient](https://api.dart.dev/stable/2.12.1/dart-io/HttpClient-class.html) from dart:io.

then developers could set proxy just like this
```dart
httpClient.findProxy = (url) => "PROXY xxxx:xxxx";
``` 

or just use project's global singleton HttpClient object directly.

Sorry for my poor english ~

**Comment by marandaneto** [comment]
@onewilk thanks for reporting, we'll discuss this internally and see how much effort :)

**Comment by marandaneto** [comment]
a downside of it would be that this lib does not support Browser Apps, so we'd need to have a specific Client for Web

**Comment by bruno-garcia** [comment]
Because of the limitation on dart2js/flutter web, I'm not sure this is the way to go.
We could add an abstraction to our use of http, and use our current implementation in the box, but allow users to swap it out as the OP requested.

**Comment by ueman** [comment]
You can set `SentryOptions.client` to use a [IOClient](https://pub.dev/documentation/http/latest/io_client/IOClient-class.html).
The IOClient constructor allows to use a dart:io HttpClient. 

That should fix the original issue.

Remarks: 
- It might be needed to also change the transport to the http transport.
- You'll loose some benefits of the native integration
- Configuration of the native SDK is tracked at #265 if you want to configure those too

As the issue should be resolved now, I think this can be closed.

We should probably document this somewhere.

What do you think, @marandaneto ?

**Comment by marandaneto** [comment]
@ueman not really, the idea is that there's an easy way to set up a proxy via options and not replacing the whole transport layer.
the current `http` lib does not allow that, but `HttpClient` does, but it does not work for Web, so we'd need to think this thoroughly

**Comment by ueman** [comment]
You can't do a proxy setup in JS though. That's why it isn't available in the HTTP package by default. 
Using the [IOClient](https://pub.dev/documentation/http/latest/io_client/IOClient-class.html) from the HTTP package does what the original issue is about. You can do this already and it works for the Dart SDK, Windows and Linux. 
For platforms with a native integration, I would say this should be done with #265

Example :
```dart
import 'dart:io';
import 'package:http/io_client.dart';
import 'package:sentry/sentry.dart';

Sentry.init(
  (options) {
    final httpClient = HttpClient(); // from dart:io
    httpClient.findProxy = (url) => "PROXY xxxx:xxxx";
    final ioClient = IOClient(httpClient); // from package:http
    options.client = ioClient;
  }
)
```

**Comment by marandaneto** [comment]
@ueman if that works, sounds good, but instead of people doing such code snippet, we could do something like:

https://github.com/getsentry/sentry-java/blob/main/sentry/src/main/java/io/sentry/SentryOptions.java#L134-L138

so they configure host, port, user, pass and we do the rest, this should be done then only by non-web env. and also, configure the native platforms for flutter (pass down the configuration when its available via message channel) as they are the ones sending the events.

if the issue is only about the proxy configuration, that's good.

the other question is, do we want to get rid of `http` package and use only `HttpClient` which is builtin on the Dart SDK?

**Comment by ueman** [comment]
> the other question is, do we want to get rid of `http` package and use only `HttpClient` which is builtin on the Dart SDK?

The built-in client is only available on dart:io.
We would have to use XHR (ort he fetch api) on web.
So basically we would need to write something like the HTTP package ourself. I would say it's not worth it.

**Comment by marandaneto** [comment]
sounds good, lets just make it easier to set up the proxy then (internally using the `IOClient`) as suggested, but let's keep the `Client` lib, this is not a breaking change anymore then but rather a feat, will remove the 6.0.0 milestone.
