### ISSUE TITLE
Adhere to Sentry version spec

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#422]
_Platform:_
- [x]  Dart
- [x]  Flutter Android or iOS
- [x]  Flutter Web

As per https://docs.sentry.io/platforms/dart/configuration/releases/#bind-the-version:

> The release name cannot:
> 
> 1. contain newlines, tabulator characters, forward slashes(`/`) or back slashes(`\`)
> 1. be (in their entirety) period (`.`), double period (`..`), or space (` `)
> 1. exceed 200 characters

Point 1. can happen in the current stable version (up to 5.0.0) but there's code and tests now (see #411) which make sure it does not happen anymore. Points 2 and 3 could still happen.

**Comment by marandaneto** [comment]
It's a valid point but I don't think it'd be possible to actually set either only `.` or only ` ` in the pubspec version, or is it?
because if it's not possible, we can close it.

if one sets `.` as release on options, it's an user's error, we don't need to validate that I guess.

also worth checking if pubspec allows 200+ chars

**Comment by ueman** [comment]
There's no indicator of length restrictions: https://dart.dev/tools/pub/pubspec#name

The Android Application Id and Version name have also no size restriction, so the 200 chars limit could be reached.

**Comment by marandaneto** [comment]
indeed, this is likely not going to happen anyway, let's not prioritize this for now

**Comment by marandaneto** [comment]
Event ingestion is going to discard if its invalid, not really needed to take care of on the SDK side, not worth doing it.
