### ISSUE TITLE
Can't catch IsolateError

### ISSUE THREAD

**Issue by JaminZhou** [getsentry/sentry-dart#607]
_Platform:_
- [x]  Dart
- [ ]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [x]  VSCode
- [ ]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [ ]  Disabled

_Platform installed with:_
- [ ] pub.dev
- [x] GitHub

Output of the command `flutter doctor -v` below:

The output goes here...

The version of the SDK (See pubspec.lock):
**6.0.1**

---
I have the following issue:

Can't catch IsolateError

**Steps to reproduce:**
change the generateError impl
```dart
....
            RaisedButton(
              child: const Text('Dart: Fail in isolate'),
              onPressed: () => isolateError(),
            ),
....

void generateError() {
  Isolate.spawn(entryPoint, "message");
}

void entryPoint(String message){
  throw StateError('Errors');
}
```

the error info in the console
```batch
[VERBOSE-2:dart_isolate.cc(1138)] Unhandled exception:
Bad state: Errors
#0      entryPoint
package:sentry_flutter_example/main.dart:136
#1      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:286:17)
#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

![image](https://user-images.githubusercontent.com/9011374/135762498-996496d5-dbb7-402c-8154-641babb4ace8.png)

**Actual result:**

Can't catch IsolateError

**Expected result:**
Catch IsolateError

**Comment by ueman** [comment]
Unfortunately this is to be expected.

Exceptions and errors in isolates other than the main isolate can't be caught automatically.

You have to set the `onError` parameter of the `Isolate.spawn()` function. [See the docs](https://api.dart.dev/stable/2.14.3/dart-isolate/Isolate/spawn.html) for more information on it.

It works for the Flutter `compute` method because they're doing it under the hood: https://github.com/flutter/flutter/blob/3595343e20a61ff16d14e8ecc25f364276bb1b8b/packages/flutter/lib/src/foundation/_isolates_io.dart

That also shows how to bring over exceptions into the main isolate.

I wonder if it makes sense to provide a `SentrySendPort` which can be used directly to make it easy to report exceptions of other isolates. So for example like this:

```dart
Isolate.spawn(entryPoint, "message", onError: SentrySendPort());
```

**Comment by JaminZhou** [comment]
@ueman thanks!

**Comment by marandaneto** [comment]
the other option is to add an `ErrorListener` to your new Isolate
See https://docs.sentry.io/platforms/flutter/usage/#tips-for-catching-errors

**Comment by marandaneto** [comment]
@ueman makes sense, either a method extension that spawns an Isolate adding `SentrySendPort` automatically or just exposing the `SentrySendPort`, would you like to submit a PR? or just create an issue :) thanks!
