### ISSUE TITLE
Cannot add attachments in a *event processor*

### ISSUE THREAD

**Issue by fzyzcjy** [getsentry/sentry-dart#646]
_Platform:_
- [ ]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

_IDE:_
- [ ]  VSCode
- [x]  IntelliJ/AS
- [ ]  XCode
- [ ]  Other, which one?

_split-debug-info and obfuscate (Flutter Android or iOS) or CanvasKit (Flutter Web):_
- [ ]  Enabled
- [x]  Disabled

_Platform installed with:_
- [x] pub.dev
- [ ] GitHub

Output of the command `flutter doctor -v` below:

unrelated

The version of the SDK (See pubspec.lock):
**latest**

---
I have the following issue:

Hi thanks for the lib! I need to attach some attachments inside a *event processor*. But I [only see](https://docs.sentry.io/platforms/dart/enriching-events/attachments/) how to do it within scopes, or by `Sentry.captureException(..., withScope: ...add my attachment...)`. However, I cannot find out a way to add attachments in event processors.

Thanks for any suggestions!

**Steps to reproduce:**
- Step

**Actual result:**
- Actual

**Expected result:**
- Result

**Comment by marandaneto** [comment]
indeed, it's not possible since the attachment isn't part of the event itself, but it's sent along with the event, and event processors only have access to the event properties.
the way to go for now is either via [scope.](https://docs.sentry.io/platforms/dart/enriching-events/attachments/#uploading-attachments) or `withScope`.
the user feedback would have the same problem since its also not part of the event itself.

why would you add it only during event processors?

**Comment by fzyzcjy** [comment]
All right... Thank you all the same, I will try to capture it together with captureException(withScope: ...)

**Comment by marandaneto** [comment]
cheers, let us know if that does not work and your use case for adding such attachments only on event processors, so we could consider it in the future.
