### ISSUE TITLE
Official support for File I/O auto performance

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-dart#835]
@ueman did it already and told us we could borrow the idea if we want to officially support those integrations https://github.com/ueman/sentry-dart-tools/tree/main/sentry_plus/lib/src/file
There's more than File IO stuff, it requires adapting to Sentry's API design and most likely tests.

**Comment by ueman** [comment]
I suggest putting the file io performance tracing into its own package. Since the file io APIs are changing from time to time it is tightly bound to the language version. 
Having it in the same package as Sentry would break the backwards compatibility.

The same applies to the network io APIs, and those changes are in different version than file io API changes.

**Comment by marandaneto** [comment]
Good to know, we can try to keep it within the sentry package if that's possible with Dart >= 2.12 and Flutter >= 2, we can also consider doing it under the v7 major branch so we can increase the min. version of Dart and Flutter, and lastly, creating a new package.

**Comment by ueman** [comment]
Dart 2.19.0 will have a breaking change which basically requires the new package solution: https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md#dartio

It's because you can be either compatible with Dart <= 2.18.x or with Dart >= 2.19.0
