### ISSUE TITLE
Report isolate name and Android thread name in `Thread` context

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#839]
_Platform:_
- [x]  Dart
- [x]  Flutter Android or iOS
- [ ]  Flutter Web

The version of the SDK (See pubspec.lock):
**6.5.0**

---
I have the following issue:

Currently the `Isolate.debugName` is added to the [`dart_context`](https://github.com/getsentry/sentry-dart/blob/e93430abb2ac24b30bb175ad3a54cb80d7671262/dart/lib/src/enricher/io_enricher_event_processor.dart#L89). This should however go into the [`Thread`](https://develop.sentry.dev/sdk/event-payloads/threads/) context, so it is linked to the exception. 

A caveat is, that throwing code executed in the [`compute`](https://api.flutter.dev/flutter/foundation/compute-constant.html) function is typically moved from the executing isolate to the main isolate. This also applies to manually spawned isolates. The reported isolate name for the exception is wrong in this case. However, this behavior can already observed in the current code.

---- 

PlatformExceptions on Android with a Java/Kotlin stack trace also do not currently report the thread name. However, if the exception includes the [thread name](https://github.com/getsentry/sentry-dart/blob/e93430abb2ac24b30bb175ad3a54cb80d7671262/flutter/lib/src/jvm/jvm_exception.dart#L30), it should also be reported via the `Thread` context.

**Comment by kuhnroyal** [comment]
Independent of `compute` it is important to get the correct name from background isolates.

**Comment by ueman** [comment]
@kuhnroyal Do you have any idea on how to do that? Because as far as I'm aware, the only way to do that is to basically do a Sentry init (with no native integration, because that doesn't work in background isolates) in each isolate and then to not let exceptions cross the isolate boundaries.

I believe for `compute` there's just no way to get the name of the isolate.

**Comment by marandaneto** [comment]
I think one solution is to offer an extension method for adding an `addErrorListener` to your own isolates.
https://github.com/getsentry/sentry-dart/issues/608

When capturing the event, you already do `captureEvent(event)` with the Isolate name set in the context already (the isolate name could be a method/ctor param to the Sentry Port).

I believe we can also change the `IsolateErrorIntegration` to do:

```
    final mechanism = Mechanism(type: 'isolateError', handled: true);
    final throwableMechanism = ThrowableMechanism(mechanism, throwable);
    final event = SentryEvent(
      throwable: throwableMechanism,
      level: SentryLevel.fatal,
      // set the isolate name using Isolate.current.debugName
    );
```

I'm not entirely sure if `Isolate.current` is gonna be the thrown Isolate or the Main one, that has to be checked.

**Comment by kuhnroyal** [comment]
@ueman I am mainly talking about isolates started from the native side via plugins (workmanager etc.) which can support plugins and native integrations. We are using a multitude of those isolates for upload/download/background_fetch and yes, there is a `Sentry.init` call in each of those but with native integration.

Exceptions are not crossing any boundaries here because there is nothing "on top" in these cases.
I think there is not much to do for these, just wanted to remind that these usages exist.


`compute` and `Isolate.spawn` are a different problem.

I am not completely sure how isolate names are determined by default. `Isolate.spawn` and `compute` have a debug label/name.
When no name is set, it sometimes seems to default to the entry point name (the top level function name) which can be obfuscated in some cases, unless `@pragma("vm:entry-point")` is set.
`compute` defaults to `debugLabel ??= kReleaseMode ? 'compute' : callback.toString();`.

But this name is not available in any exception. 


@marandaneto I am pretty sure the `Isolate.current` is the main isolate, because the stack trace in isolate error handlers is a `String` after it has been serialized across. So the integration won't help us there. The errors are send via `SendPort`.

I think we should be able to wrap those in something like `SentryFlutter.compute/spawn({String debugName = 'compute'})` and use this name in the error handling.

**Comment by ueman** [comment]
> I think we should be able to wrap those in something like SentryFlutter.compute/spawn({String debugName = 'compute'}) and use this name in the error handling.

Or create an extension method on isolate which internally calls `addErrorListener`. If we have access to the isolate we can just call isolate.debugName

> I am mainly talking about isolates started from the native side via plugins (workmanager etc.) which can support plugins and native integrations.

Can you manually set the name of those isolates? Or do they have the default name?

**Comment by kuhnroyal** [comment]
> If we have access to the isolate we can just call isolate.debugName

For `(await Isolate.spawn(...)).handleErrorWithSentry()` this could work. For `compute` we don't have access to the instance. 

> Can you manually set the name of those isolates? Or do they have the default name?

Not sure, have not tried that myself, only relied on plugins so far. But the entry point name is the default here as well. The main isolate is called `main` because of `void main()` :) and with some plugins the isolate name changes depending on your own entry point name.

**Comment by marandaneto** [comment]
> @ueman Can you manually set the name of those isolates? Or do they have the default name?

Yes, `Isolate.spawn` has a optional `debugName`.

Yeah, we have to try out and see what makes more sense.
PRs are welcomed by the way :)
