### ISSUE TITLE
Document how to test Sentry Flutter

### ISSUE THREAD

**Issue by ccadieux** [getsentry/sentry-dart#863]
Just upgraded from 5.1.0 -> 6.5.1

Previous we could capture the event and then use expect against the throwable.
```
  SentryEvent? verifyEvent([dynamic throwable]) {
    SentryEvent? event = verify(() => transport.send(captureAny()))
        .captured
        .first as SentryEvent?;
    if (throwable != null) {
      expect(event!.throwable, throwable);
    }
    return event;
  }
```

Now with SentryEnvelope all I can do is verify there was an event. I tried decoding it but throwable is not serialized. 

There doesn't seem to be a way to provide a MockHub like I see in your tests.

Is there any guidance on how to test Sentry?

**Comment by marandaneto** [comment]
@ccadieux Maybe`verify` the `SentryClient` instead of the `transport`?
At this point, the `throwable` is still there.

You can also verify the serialized version of the `throwable`, instead of checking its instances.
You can also see how the method `eventFromEnvelope` is used in the tests, so you make an event out of the envelope. 

Both would work :)
