### ISSUE TITLE
Performance tracing should use Timeline

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry-dart#961]
The Dart Dev tools include a performance view similar to the one of Sentry, see 

- https://dart.dev/tools/dart-devtools
- https://docs.flutter.dev/development/tools/devtools/performance
- https://docs.flutter.dev/development/tools/devtools/cpu-profiler

If Sentry adds Timeline events (see [Timeline](https://api.dart.dev/stable/2.17.6/dart-developer/Timeline-class.html) and [TimelineTask](https://api.dart.dev/stable/2.17.6/dart-developer/TimelineTask-class.html)) it could also double for debugging performance in debug mode.

**Comment by marandaneto** [comment]
I guess that's something we'd like to explore in the future, but right now we are focused on what can be measured in production only.
You can still create your own integration and send the data over to Sentry, but that's not something we'd be adding by default since it's debugging mode only.
Maybe @bruno-garcia has opinions.

**Comment by marandaneto** [comment]
Somehow relates to https://github.com/getsentry/sentry-dart/issues/721
Cus it mentions the timeline task.

**Comment by marandaneto** [comment]
Since Sentry is focused on Production monitoring, I'll close this in favor of https://github.com/getsentry/sentry-dart/issues/1106
